name: Nightly Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Rename distribution files
        run: |
          mkdir -p nightly
          cp dist/*.whl nightly/tkintercli-nightly-build.whl
          cp dist/*.tar.gz nightly/tkintercli-nightly-build.tar.gz

      - name: Get recent commit messages
        id: get_commits
        run: |
          COMMIT_LIST=$(git log -10 --pretty=format:"- [\`%h\`](https://github.com/${{ github.repository }}/commit/%H) %s" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g')
          echo "commits<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMIT_LIST" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Delete previous nightly release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          tag_name: nightly
          delete_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Create nightly release
        uses: softprops/action-gh-release@v1
        with:
          name: "Nightly Release (${{ steps.date.outputs.date }})"
          tag_name: nightly
          body: |
            **Nightly build** créée automatiquement le ${{ steps.date.outputs.date }}
            
            ## Derniers commits
            ${{ steps.get_commits.outputs.commits }}
            
            Cette version est une pré-release et peut contenir des bugs.
          prerelease: true
          files: |
            nightly/tkintercli-nightly-build.whl
            nightly/tkintercli-nightly-build.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}